In [10]:
import pandas as pd

In [11]:
df_green = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet')
df_zones = pd.read_csv('https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv')

In [12]:
df_green.head(10)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.00
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.00
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.00
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.00
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.00
5,1,2025-11-01 00:42:13,2025-11-01 01:04:50,N,1.0,112,48,2.0,5.10,26.8,...,1.5,6.55,0.0,NaN,1.0,39.35,1.0,1.0,2.75,0.75
6,2,2025-11-01 00:05:41,2025-11-01 00:39:20,N,1.0,83,87,1.0,9.80,43.6,...,0.5,9.92,0.0,NaN,1.0,59.52,1.0,1.0,2.75,0.75
7,2,2025-11-01 00:42:14,2025-11-01 01:13:20,N,1.0,66,233,1.0,5.01,28.9,...,0.5,6.98,0.0,NaN,1.0,41.88,1.0,1.0,2.75,0.75
8,2,2025-11-01 00:03:08,2025-11-01 00:06:27,N,1.0,223,223,1.0,0.63,5.1,...,0.5,1.52,0.0,NaN,1.0,9.12,1.0,1.0,0.00,0.00
9,2,2025-11-01 00:56:33,2025-11-01 01:01:34,N,1.0,130,130,1.0,1.15,7.9,...,0.5,0.00,0.0,NaN,1.0,10.40,2.0,1.0,0.00,0.00

In [13]:
df_zones.head(10)

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone
5           6  Staten Island  Arrochar/Fort Wadsworth    Boro Zone
6           7         Queens                  Astoria    Boro Zone
7           8         Queens             Astoria Park    Boro Zone
8           9         Queens               Auburndale    Boro Zone
9          10         Queens             Baisley Park    Boro Zone

In [14]:
df_zones.dtypes

LocationID      int64
Borough           str
Zone              str
service_zone      str
dtype: object

In [15]:
!uv add sqlalchemy "psycopg[binary,pool]"

Resolved 104 packages in 0.92ms
Checked 100 packages in 1ms

In [16]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi_green')

In [17]:
print(pd.io.sql.get_schema(df_green, name='green_taxi_data', con=engine))

CREATE TABLE green_taxi_data (
	"VendorID" INTEGER,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" FLOAT(53),
	"PULocationID" INTEGER,
	"DOLocationID" INTEGER,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type FLOAT(53),
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

In [20]:
print(pd.io.sql.get_schema(df_zones, name='taxi_zone_data', con=engine))

CREATE TABLE taxi_zone_data (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [42]:
df_zones_iter = pd.read_csv('https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv', iterator=True, chunksize=100000)

In [43]:
chunk_size = 100000
first = True

for start in range(0, len(df_green), chunk_size):
    chunk = df_green.iloc[start:start + chunk_size]

    if first:
        chunk.head(0).to_sql(
            name="green_taxi_data",
            con=engine,
            if_exists = "replace",
            index=False
        )
        first = False
        print("Table Created")
        
    chunk.to_sql(
        name="green_taxi_data",
        con=engine,
        if_exists="append",
        index=False
    )

    print("Inserted:", len(chunk))

Table Created
Inserted: 46912

In [44]:
first = True

for df_chunk in df_zones_iter:

    if first:
        df_chunk.head().to_sql(
            name="taxi_zone_data",
            con=engine,
            if_exists = "replace")
        first = False
        print("Table Created")

    df_chunk.to_sql(
        name="taxi_zone_data",
        con=engine,
        if_exists = "append",
        index=False
    )

    print("Inserted:", len(df_chunk))

Table Created
Inserted: 265